### ISSUE TITLE
Usage?

### ISSUE THREAD

**Issue by wayner9** [MizterB/InfinityTouch#1]
How do you actually use this package to change your temperature?  Or to read your temperature?

**Comment by MizterB** [comment]
Long story short, I wouldn't :)

This started as an attempt to replicate the features of [Infinitude](https://github.com/nebulous/infinitude) proxy server in Python, at a time when that project wasn't receiving regular updates and was broken for me.  However, development resumed on that project and I strongly recommend you use it for a local management API.  

The Infinitude proxy can now be deployed via Docker for quick & easy setup, and I've been using it without issue for a couple of years now.  If you are looking for examples of how to interface with it via Python, you can check out my [Infinitude integration for HomeAssistant](https://github.com/MizterB/homeassistant-infinitude)
